### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lucaruzzola** [mattiaivaldi/TRACKS#16]
Why are parameters named a,b,c,d instead of more explicit names?
What is CPU time and run time?

The project really should be organized into modules and folders, and shared object should be in the same directory as the rest of the code.

If you have boolean variables I don't see the point in doing if(paolonoise==True), you can just write if(paolonoise).

The code is overall good, but it lacks a bit or organization and of software engineering, which should not be optional or an afterthought but rather guidelines to follow from the beginning.

Prints in a production-grade system are not ok, you should look into a logging library.

8/10

**Comment by mattiaivaldi** [comment]
Parameters naming system follows Root convention of assigning letters to integer or boolean parameters, e.g. gStyle->SetOptFit(p,c,e,v).

CPU time is the time used by the CPU for a specific process (e.g. it does not count I/O time). Run time is the actual time used by the device to execute the whole program. Ideally one wants the two to be equal, so that the CPU efficiency defined as CPU time/(Run time*# cpus) equals 1.

Good point about the if control with boolean, we didn't realise that.

What do you mean about the organisation into modules, folders, and shared objects? Consider that Root wants all the used code in the same directory.

Also I don't get the point about the production-grade system printing, can you explain it?

Thx

**Comment by lucaruzzola** [comment]
I don't see such a convention listed [here](https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#conventions), and still, more explicit single letter variables could be used. Also, you have variables that do not follow this convention.

Why are you interested in that kind of efficiency rather than in computational efficiency? One should write code to minimize the amount of cpu time first, I think.
Does having good CPU efficiency only mean you are not doing I/O ?
Also, would you consider inefficient a program that takes time to write stuff to memory and/or disk rather than only on doing calculations, but that still takes less time?

Are you sure Root needs that? I don't see any mention of that in the documentation.
Here is an example of [code organisation ](https://stackoverflow.com/questions/15202368/organising-code-in-c)in c++.
Shared objects are .so files, I feel like those should not be together with the code.

A logging system makes it easier to find out what went wrong when something breaks or takes forever, [here](https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print) is an answer about Python. Basically it's about having a standardized and information rich way to output data to stdout or stderr instead of just printing.

**Comment by lucaruzzola** [comment]
By they way, my example about efficiency makes little sense ahahah

**Comment by mattiaivaldi** [comment]
Well, I think it depends. Keeping the I/O case, if you have to handle large volumes of data (an example [here](https://en.wikipedia.org/wiki/Worldwide_LHC_Computing_Grid)) you can't avoid it, but rather you should minimize that time wrt the computational time. If your software is excellent in doing math, but very bad in I/O, storing, etc., then it's inefficient.

When I compile the classes through Root all the _extra_ files (.d, .so, etc.) are created in the same folder. If I remove, for instance, the .so and compile them again it does not work. So at this stage we are keeping everything here, but we are looking for a better solution in terms of code organisation.

All the printing in the code is actually both for debugging and for getting info about the physics. The logging is anyway a good hint!

**Comment by mattiaivaldi** [comment]
BTW we just realised at least two ways to avoid uploading the _extra files_: naively with a gitignore, otherwise we found out how to force them in a hidden local folder.

I'm closing this issue!
